trigger:
- main # Cambia 'main' por la rama que activará el pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHub' # La Service Connection a Docker Hub
  imageName: 'python:3.10-alpine' # Reemplaza con el nombre de tu imagen en Docker Hub
  targetImageName: '$(imageName)' # El nombre de la imagen final que quieres usar

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    - checkout: self
      displayName: "Clonar el repositorio"

    # Autenticarse en Docker Hub
    - task: Docker@2
      displayName: "Login en Docker Hub"
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    # Traer la imagen base desde Docker Hub
    - script: |
        echo "Descargando imagen base desde Docker Hub..."
        docker pull $(imageName)
      displayName: "Pull de imagen base desde Docker Hub"

    # Construir la nueva imagen usando el Dockerfile en la carpeta app
    - task: Docker@2
      displayName: "Construir imagen Docker desde app/Dockerfile"
      inputs:
        command: build
        dockerfile: app/Dockerfile # Ruta al Dockerfile en la carpeta app
        buildContext: app          # Contexto de construcción en la carpeta app
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(targetImageName)
        tags: |
          $(Build.BuildId)

    # Subir la imagen construida a Docker Hub
    - task: Docker@2
      displayName: "Push de la imagen a Docker Hub"
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(targetImageName)
        tags: |
          $(Build.BuildId)