trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - azure-pipelines.yml  
      
pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHub' 
  sonarQubeServiceConnection: 'SonarQube'
  imageName: '$(DockerImageName)'
  imageTag: '$(Build.BuildId)' 

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    
    - checkout: self
      displayName: "Clonar el repositorio"
      fetchDepth: 0

    
    - task: SonarQubePrepare@7
      displayName: "Preparar análisis de SonarQube"
      inputs:
        SonarQube: $(sonarQubeServiceConnection)
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: '$(SONARQUBE_PROJECT_KEY)'

    
    - script: |
        echo "Compilando o preparando el proyecto para análisis..."
        # Aquí puedes ejecutar compilación, pruebas, o pasos previos necesarios para SonarQube
      displayName: "Construir y preparar para SonarQube"

    
    - task: SonarQubeAnalyze@7
      displayName: "Ejecutar análisis de SonarQube"
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

#    # Publicar los resultados del análisis en SonarQube
#    - task: SonarQubePublish@7
#      displayName: "Publicar resultados de SonarQube"
#      inputs:
#        pollingTimeoutSec: '300'

   
    - task: Docker@2
      displayName: "Login en Docker Hub"
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    
    - task: Docker@2
      displayName: "Construir imagen Docker desde app/Dockerfile"
      inputs:
        command: build
        dockerfile: app/Dockerfile
        buildContext: app
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(imageTag)


    - task: Docker@2
      displayName: "Push de la imagen a Docker Hub"
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(imageTag)
    
- stage: Deploy
  displayName: "Deploy to EKS"
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to Kubernetes
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: "Test Kubernetes Connection"
      inputs:
        kubernetesServiceEndpoint: 'KubernetesConnection' 
        command: 'get'
        arguments: 'nodes'
    - task: Kubernetes@1
      displayName: "Set Kubernetes Context"
      inputs:
        kubernetesServiceEndpoint: 'KubernetesConnection' 
        namespace: $(kubernetesNamespace)
    - script: |
        kubectl apply -f namespace.yaml --validate=false
        kubectl apply -f deployment.yaml --validate=false
        kubectl apply -f service.yaml --validate=false
        kubectl apply -f ingress.yaml --validate=false
      displayName: Deploy Kubernetes Manifests
