#apiVersion: v1
#kind: Service
#metadata:
#  name: web-service
#  namespace: samtel
#spec:
#  selector:
#    app: web
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8000
#  type: ClusterIP


#apiVersion: v1
#kind: Service
#metadata:
#  name: web-service
#  namespace: samtel
#spec:
#  selector:
#    app: web
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8000
#      nodePort: 30080 # Especifica un puerto entre 30000-32767
#  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: samtel
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer